### ISSUE TITLE
stick сс2530 can not connect with coordinator сс2531

### ISSUE THREAD

**Issue by Ruchechnik** [dzungpv/dnckatsw00x#1]
hi  loved your script control relay!  
but I can not understand : I have is "iobroker", stick cc2531 manages this plugin- https://github.com/ioBroker/ioBroker.zigbee
I connect your firmware sewn ss2530 and coordinator of my network ss2531. 
I do not understand, in the list of devices there is a button, but I change its state (true or false) on your module I can not find high or low level ((help to understand

**Comment by Ruchechnik** [comment]
thanks , I figured out connection ) Everything works !
 Can you put the firmware version for 4 relays ?

**Comment by dzungpv** [comment]
@Ruchechnik you can build your own with my guide
