### ISSUE TITLE
How to  add it to homeassistant

### ISSUE THREAD

**Issue by Jinvis** [dzungpv/dnckatsw00x#10]
Hi,
I have downloaded  Z-Stack Home 1.2.2a  and modify it as yours, then download the hex to my cc2530, but it seems zigbee2mqtt  can not find my device, i do not know why. By the way, can i get your CCDefines of the project ?  may be there is some wrong defines in my project.

Thanks.

**Comment by dzungpv** [comment]
You can reinstall and apply the patch: https://github.com/dzungpv/dnckatsw00x/blob/master/dnckatsw001.patch It include all changes make project running and connect to HA
