### ISSUE TITLE
CC1352 wiring

### ISSUE THREAD

**Issue by guitar9** [dzungpv/dnckatsw00x#13]
So this is a little bit off topic.
@dzungpv  
I want to ask you how to exactly wire the CC1352. I am using zibgee2mqtt.
you said to wire Xds110 or later with 4 pin, TMS, TCK, Reset, GND, VCC(3.3V).

in XDS110 there is no TMS. At how to connect the USB Interface?

XDS110 Pin Mapping:
![XDS110](https://user-images.githubusercontent.com/25721108/74560551-158cdb80-4f67-11ea-951d-ce06d3de51a2.png)

XDS110:
![XDS110](https://user-images.githubusercontent.com/25721108/74560893-ca26fd00-4f67-11ea-960b-083099d5737c.jpeg)

CC1352
![CC1352](https://user-images.githubusercontent.com/25721108/74560900-d0b57480-4f67-11ea-8099-27665e53757c.jpeg)

**Comment by dzungpv** [comment]
Pin number 1, XDS110 do not have VCC so you must power it with 3.3V

**Comment by guitar9** [comment]
ok thank you very much. At which PIN I must Power the XDS110? And for Ground I can choose 8,10,12,16 or 20?
Should I wire the 3.3 V also at VCC and GND of the CC1352?
And where to connect RXD and TXD of the USB interface?

**Comment by dzungpv** [comment]
Pin 5 of the XDS110 VREF to +3.3V, Ground you can choose any pin.
TX pin to IO12
RX pin to IO13

**Comment by tkwant** [comment]
Did I forgot something?
![1](https://user-images.githubusercontent.com/43744627/74786062-1f3a7a00-52ac-11ea-89c2-986ce84cdf6d.jpeg)
![2](https://user-images.githubusercontent.com/43744627/74786074-22ce0100-52ac-11ea-8a6b-b0e2fd7d9bab.jpeg)

**Comment by guitar9** [comment]
Did I forgot something?
![1](https://user-images.githubusercontent.com/25721108/74786762-cbc92b80-52ad-11ea-97d2-8f214efd4452.jpeg)
![2](https://user-images.githubusercontent.com/25721108/74786767-ce2b8580-52ad-11ea-8a34-8ed3ddc2c4c9.jpeg)

**Comment by dzungpv** [comment]
ResetN to Xds Nreset.
Note that only wire TMS, TCK, Reset to Xds when you are programing the chip. After that disconnect it and use only 4 pin VCc, GNd, TX, Rx when use zigbee2mqtt

**Comment by guitar9** [comment]
Flashing works fine but when I use zigbee2mqtt I get error Error: AREQ - SYS - resetInd after 30000ms
According to this thread I should press software reset button. Do you know how I do this without dev board? Or do you have another idea? I am using CC1352P https://github.com/Koenkk/zigbee2mqtt/issues/2162

**Comment by dzungpv** [comment]
You flash the wrong firmare, you chip is cc1352 but 20dbm for 433/900mhz not for 2.4Ghz/zigbee. You must build your own firmware, see the guide in the firmware repo, but choose "znp_cc1352p1"

**Comment by guitar9** [comment]
Cant find znp_cc1352p1.
Where can I buy cc1352p-2 chip? I only found cc1352P Microcontroller at texas instruments. 
I only found CC1352p-2 as dev board. 

![image](https://user-images.githubusercontent.com/25721108/74973862-8a0ec100-5424-11ea-9d90-f99f2176bde1.png)

**Comment by dzungpv** [comment]
You can try CC1352P2 variant and disable high power mode, you can see in TI docs https://www.ti.com/tool/LAUNCHXL-CC1352P

And this is my last answer here. You can ask for help in TI forum https://e2e.ti.com/support/wireless-connectivity/zigbee-and-thread/f/158

**Comment by guitar9** [comment]
Thank you!
I think I should first start with Simple SDK Basics. Do you know a good point to start with zigbee?
