### ISSUE TITLE
problems connecting сс2530 after removing it

### ISSUE THREAD

**Issue by Ruchechnik** [dzungpv/dnckatsw00x#3]
I have a problem: I tested the device for a long time, everything works without problems.  but once removed from the system , it will not connect again! Flashing the device and coordinator does not solve the problem ((what could be the matter ?

**Comment by dzungpv** [comment]
Please follow this guide https://github.com/dzungpv/dnckatsw00x/issues/9#issuecomment-503435441 and check the patch file for SampleLight project
