### ISSUE TITLE
8 Channels

### ISSUE THREAD

**Issue by khzd** [dzungpv/dnckatsw00x#4]
Hi
do you think it's possible to change your code to manage 8 channel?

thanks

**Comment by khzd** [comment]
Hi any chance to have a support ?

**Comment by dzungpv** [comment]
It is posible, you can try youself, just use more EP

**Comment by khzd** [comment]
Hi thanks for your feedback
I also need to add it in zigbee2mqtt, and have a standard distribution. 
What about to use your git ?
Cheers

**Comment by khzd** [comment]
Hi any chance to have a support ?

**Comment by khzd** [comment]
Hi any chance to have a support ?
I do not have a windows system, can you provide me a way to do this on a unix platform?
Cheers

**Comment by dzungpv** [comment]
@khzd You can use VMware and run Windows or use AWS EC2 , Zstack 1.2.2 only running on Windows.
About the zigbee2mqtt you can see my code for 4 channel model and add more to it.

**Comment by khzd** [comment]
Ok thanks, I will give a try
