### ISSUE TITLE
Does not reconnect to coordinator after reset

### ISSUE THREAD

**Issue by iot7272** [dzungpv/dnckatsw00x#5]
Everything works great. But the state of the relay and the network does not retain after the reset of the device (cc2530). Once the device is reset, I have to permit joining from the coordinator again in order to connect cc2530.
Could you please provide some info regarding this?
Thank you

**Comment by dzungpv** [comment]
Do you mean you unplug/ cut the power to cc2530?

**Comment by iot7272** [comment]
Yes. And even pressing the reset button.

**Comment by iot7272** [comment]
Is there any workaround for this? Any help would be much appreciated.

**Comment by dzungpv** [comment]
@iot7272 change  xNV_RESTORE to NV_RESTORE in your project settings
