### ISSUE TITLE
Patch for the changes

### ISSUE THREAD

**Issue by iot7272** [dzungpv/dnckatsw00x#6]
I had added the report code to the Sample Light source code from Z Stack 1.2. but was not able to connect to HomeAssistant. I also tested by changing the Channels. Could you please share a patch containing the required changes?

Thanks in advance

**Comment by dzungpv** [comment]
@iot7272 you can download it here: https://github.com/dzungpv/dnckatsw00x/blob/master/dnckatsw001.patch
