### ISSUE TITLE
How to join the zigbee network?

### ISSUE THREAD

**Issue by nobodyman1** [dzungpv/dnckatsw00x#7]
Could you please explain how to join the zigbee network? If there is a button required please mention the corresponding digital input of the CC2530.
Thank you!

**Comment by shahglobal** [comment]
I have the same question.
Thanks

**Comment by shahglobal** [comment]
Sniffer showed showed beacons on 2425Mhz, while zigbee2mqtt was on 2405,, how can I change its channel to Match zigbee2mqtt dongle?
Thanks

**Comment by olili** [comment]
same problem/question. Any hint?

**Comment by VertorixAU** [comment]
I'm also wondering how to add this to the zigbee network?  It is odd that it would only work on a single channel, and the default one is different to the zigbee2MQTT default for the CC2531.  Shouldn't it be able to be added to any channel?

Anyone had success with this firmware?

**Comment by dzungpv** [comment]
I use channel 15 for the firmware, just change in zigbee2mqtt settings,
To change the channel to all edit file: C:\Texas Instruments\Z-Stack Home 1.2.2a.44539\Projects\zstack\Tools\CC2530DB\f8wConfig.cfg
Example below use all vavilable channel:
```
-DDEFAULT_CHANLIST=DMAX_CHANNELS_24GHZ
```
